# Generated by Django 5.0.2 on 2024-06-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Identification_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=128)),
                ('number', models.IntegerField(max_length=10, unique=True)),
                ('personal_number', models.IntegerField(max_length=10, null=True)),
                ('spam', models.BooleanField(default=False)),
            ],
        ),
    ]
